server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    password: atharva
    url: jdbc:postgresql://localhost:5432/fraud
    username: atharva
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka